### PR TITLE
Update generator.py

### PR DESCRIPTION
**Pull request by irealmatin**
I enjoy the OOP paradigm.

### CODE REVIEW

**Comment by BaseMax** [comment]
- `def read_names(file_path):`
- `def Design_Certificate(name):`
- `def create_certificates(names):`

First, thank you for contributing to the project.
Second, It's better to follow one styling for naming the functions.

Best,
M.

**Comment by BaseMax** [comment]
It's better to delete the contents of the `names.txt` file and use the following contents:
https://1000randomnames.com/

Do not forget to change function names.

**Comment by BaseMax** [comment]
It will be good if we move `f"certificate-{name.replace(' ', '-').lower()` functionality to a separate function.

**Comment by irealmatin** [comment]
Thank you for the advice.
ok , I will definitely change the names of `name.txt` file .

**Comment by irealmatin** [comment]
yes you can do that
like this 
```python
def Certificate_Filename(name):
    return os.path.join(OUTPUT_DIR_PATH, f"certificate-{name.replace(' ', '-').lower()}.png")
```
add it to my code and then define a output_filename and use this function

**Comment by BaseMax** [comment]
Commit and push these, I will re-review them again.

Best wishes

**Comment by irealmatin** [comment]
now this code is more readable and modular ,
 you can merge it :))

Best wishes Ali ,

Matin

**Comment by BaseMax** [comment]
You must note you need to do all your change in one commit. Not 7 commits for small changes. In addition, you can search more about how to merge your commits into one.

Anyway, I merge it for now.
Thank you for your contribution.

**Pull request merged**
